-- ------------------------------------------------------------
-- EXERCICE
-- Catalogue des exercices de référence
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS exercices
(
    exercice_id        INTEGER GENERATED BY DEFAULT AS IDENTITY,
    exercice_ref       INTEGER,
    type_exercice      VARCHAR(10) NOT NULL,
    categorie_exercice VARCHAR(10) NOT NULL,
    exercice_code      VARCHAR(50) NOT NULL,
    estimate_value     NUMERIC(1, 2),
    CONSTRAINT pk_exercices PRIMARY KEY (exercice_id),
    CONSTRAINT uq_exercices_1 UNIQUE (exercice_code),
    CONSTRAINT fk_exercices_1 FOREIGN KEY (exercice_ref) REFERENCES exercices (exercice_id),
    CONSTRAINT chk_exercices_1 CHECK (type_exercice IN ('SQUAT', 'PULL', 'SNATCH', 'CLEAN', 'JERK', 'MUSCU')),
    CONSTRAINT chk_exercices_2 CHECK (categorie_exercice IN ('TECH', 'COMBI', 'SEMI_LEGER', 'SEMI_LOURD', 'RENFO', 'GEN', 'LEG', 'POST', 'CORE', 'CARDIO', 'PLYO'))
);

COMMENT ON TABLE exercices IS 'Catalogue des exercices de référence';
COMMENT ON COLUMN exercices.exercice_ref IS 'Référence vers un exercice parent (auto-référence)';
COMMENT ON COLUMN exercices.type_exercice IS 'Type d''exercice : SQUAT, PULL, SNATCH, CLEAN, JERK, MUSCU';
COMMENT ON COLUMN exercices.categorie_exercice IS 'Catégorie d''exercice ou groupe musculaire : TECH, COMBI, SEMI_LEGER, SEMI_LOURD, RENFO, GEN, LEG, POST, CORE, CARDIO, PLYO';
COMMENT ON COLUMN exercices.exercice_code IS 'Code unique identifiant l exercice (voir libellé dans les fichiers i18n)';
COMMENT ON COLUMN exercices.estimate_value IS 'Charge théorique (% de l''exercice de référence)';

-- ------------------------------------------------------------
-- CORRECTION
-- Table de liaison exercice → exercices correctifs
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS corrections
(
    exercice_id   INTEGER NOT NULL,
    correction_id INTEGER NOT NULL,
    CONSTRAINT pk_corrections PRIMARY KEY (exercice_id, correction_id),
    CONSTRAINT fk_corrections_1 FOREIGN KEY (exercice_id) REFERENCES exercices (exercice_id),
    CONSTRAINT fk_corrections_2 FOREIGN KEY (correction_id) REFERENCES exercices (exercice_id)
);

COMMENT ON TABLE corrections IS 'Exercices correctifs associés à un exercice principal';

-- ------------------------------------------------------------
-- ATHLETE
-- Fiche athlète
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS athletes
(
    athlete_id       INTEGER GENERATED BY DEFAULT AS IDENTITY,
    first_name       VARCHAR(50) NOT NULL,
    last_name        VARCHAR(50) NOT NULL,
    sexe             VARCHAR(1)  NOT NULL,
    age_categorie    VARCHAR(10),
    weight_categorie INTEGER,
    comp_level       VARCHAR(10),
    CONSTRAINT pk_athletes PRIMARY KEY (athlete_id),
    CONSTRAINT chk_athletes_1 CHECK (sexe IN ('M', 'F')),
    CONSTRAINT chk_athletes_2 CHECK (age_categorie IN ('U15', 'U17', 'U20', 'SEN', 'MASTER')),
    CONSTRAINT chk_athletes_3 CHECK (weight_categorie IN (41, 45, 49, 51, 53, 55, 57, 60, 61, 65, 69, 70, 75, 77, 85, 86, 95, 110, 999)),
    CONSTRAINT chk_athletes_4 CHECK (comp_level IN ('DEB', 'DPT', 'REG', 'IRG', 'HON', 'NAT', 'EUR', 'MON'))
);

COMMENT ON TABLE athletes IS 'Fiche athlète OBC';
COMMENT ON COLUMN athletes.sexe IS 'M = Masculin, F = Féminin';
COMMENT ON COLUMN athletes.age_categorie IS 'Catégorie d âge : U15, U17, U20, SEN, MASTER';
COMMENT ON COLUMN athletes.weight_categorie IS 'Catégorie de poids | Hommes : 51, 55, 60, 65, 70, 75, 85, 95, 110, 999 (supérieur à 110) | Femmes : 41, 45, 49, 53, 57, 61, 69, 77, 86, 999 (supérieur à 86) ';
COMMENT ON COLUMN athletes.comp_level IS 'Niveau de compétition : DEB, DPT, REG, IRG, HON, NAT, EUR, MON';

-- ------------------------------------------------------------
-- REF_ARCHETYPE
-- Table de référence des archétypes force-vitesse
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ref_archetypes
(
    ref_archetype_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    archetype        VARCHAR(10) NOT NULL,
    strength_speed   VARCHAR(10)  NOT NULL,
    technique        VARCHAR(10)  NOT NULL,
    endurance        VARCHAR(10)  NOT NULL,
    CONSTRAINT pk_ref_archetypes PRIMARY KEY (ref_archetype_id),
    CONSTRAINT uq_ref_archetypes_1 UNIQUE (archetype, strength_speed, technique, endurance),
    CONSTRAINT chk_ref_archetypes_1 CHECK (strength_speed IN ('STRENGTH', 'MID', 'SPEED')),
    CONSTRAINT chk_ref_archetypes_2 CHECK (technique IN ('LOW', 'MID', 'HIGH')),
    CONSTRAINT chk_ref_archetypes_3 CHECK (endurance IN ('LOW', 'MID', 'HIGH')),
    CONSTRAINT chk_ref_archetypes_4 CHECK (archetype IN ('MID', 'ROUGH', 'TECH', 'CYCLE', 'LEARN'))
);

COMMENT ON TABLE ref_archetypes IS 'Table de référence des archétypes de profil athlète';
COMMENT ON COLUMN ref_archetypes.archetype IS 'Nom de l''archétype : MID, ROUGH, TECH, CYCLE, LEARN';
COMMENT ON COLUMN ref_archetypes.strength_speed IS 'Niveau force-vitesse : STRENGTH, MID, SPEED';
COMMENT ON COLUMN ref_archetypes.technique IS 'Niveau technique : LOW, MID, HIGH';
COMMENT ON COLUMN ref_archetypes.endurance IS 'Niveau endurance : LOW, MID, HIGH';

-- ------------------------------------------------------------
-- EVAL_SUMMARY
-- Bilan d évaluation d un athlète
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS eval_summaries
(
    evaluation_id    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    athlete_id       INTEGER NOT NULL,
    evaluation_date  DATE NOT NULL,
    archetype        VARCHAR(10),
    strength_speed   VARCHAR(10),
    technique        VARCHAR(10),
    endurance        VARCHAR(10),
    squat            VARCHAR(10),
    pull             VARCHAR(10),
    snatch_strength  VARCHAR(100),
    snatch_weakness  VARCHAR(100),
    clean_strength   VARCHAR(100),
    clean_weakness   VARCHAR(100),
    jerk_strength    VARCHAR(100),
    jerk_weakness    VARCHAR(100),
    psycho_strength  VARCHAR(100),
    psycho_weakness  VARCHAR(100),
    CONSTRAINT pk_eval_summaries PRIMARY KEY (evaluation_id),
    CONSTRAINT fk_eval_summaries_1 FOREIGN KEY (athlete_id) REFERENCES athletes (athlete_id)
);

COMMENT ON TABLE eval_summaries IS 'Bilan synthétique d une évaluation athlète';
COMMENT ON COLUMN eval_summaries.archetype IS 'Archétype résultant de l''évaluation : MID, ROUGH, TECH, CYCLE, LEARN';
COMMENT ON COLUMN eval_summaries.strength_speed IS 'Profil force-vitesse : STRENGTH, MID, SPEED';
COMMENT ON COLUMN eval_summaries.technique IS 'Profil technique : LOW, MID, HIGH';
COMMENT ON COLUMN eval_summaries.endurance IS 'Profil endurance : LOW, MID, HIGH';
COMMENT ON COLUMN eval_summaries.squat IS 'Profil squat : STRENGTH, MID, SPEED';
COMMENT ON COLUMN eval_summaries.pull IS 'Profil tirage : STRENGTH, MID, SPEED';
COMMENT ON COLUMN eval_summaries.snatch_strength IS 'Point fort à l''arraché';
COMMENT ON COLUMN eval_summaries.snatch_weakness IS 'Point faible à l''arraché';
COMMENT ON COLUMN eval_summaries.clean_strength IS 'Point fort à l''épaulé';
COMMENT ON COLUMN eval_summaries.clean_weakness IS 'Point faible à l''épaulé';
COMMENT ON COLUMN eval_summaries.jerk_strength IS 'Point fort au jeté';
COMMENT ON COLUMN eval_summaries.jerk_weakness IS 'Point faible au jeté';
COMMENT ON COLUMN eval_summaries.psycho_strength IS 'Point fort psychologique : CALM, CONFIDENT, MOTIVATED, FOCUSED, COMPETITIVE, CHALLENGER, INDEPENDANT';
COMMENT ON COLUMN EVAL_SUMMARIES.psycho_weakness IS 'Point faible psychologique : EMOTIONAL, ANXIOUS, INDIFFERENT, DISTRACTED, HEDONISTIC, PRAGMATIC, RULE';

CREATE INDEX IF NOT EXISTS idx_eval_summaries_1 ON eval_summaries (athlete_id);
CREATE INDEX IF NOT EXISTS idx_eval_summaries_2 ON eval_summaries (evaluation_date);

-- ------------------------------------------------------------
-- EVAL_DETAIL
-- Détail des mesures par évaluation
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS eval_details
(
    evaluation_detail_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    evaluation_id        INTEGER NOT NULL,
    eval_categorie       VARCHAR(10) NOT NULL,
    exercice_code        VARCHAR(50),
    real_value           NUMERIC(10, 4),
    result               INTEGER,
    CONSTRAINT pk_eval_details PRIMARY KEY (evaluation_detail_id),
    CONSTRAINT fk_eval_details_1 FOREIGN KEY (evaluation_id) REFERENCES eval_summaries (evaluation_id)
);

COMMENT ON TABLE eval_details IS 'Détail des mesures réalisées lors d une évaluation';
COMMENT ON COLUMN eval_details.eval_categorie IS 'Catégorie de l évaluation : STRENGTH, TECH, CARDIO, PSYCHO';
COMMENT ON COLUMN eval_details.exercice_code IS 'Code de l''exercice évalué';
COMMENT ON COLUMN eval_details.real_value IS 'Valeur mesurée (kg, m/s, %, reps, etc.)';
COMMENT ON COLUMN eval_details.result IS 'Résultat calculé : LOW (-1), MID (0), HIGH (1)';

CREATE INDEX IF NOT EXISTS idx_eval_details_1 ON eval_details (evaluation_id);

-- ------------------------------------------------------------
-- PROG
-- Programme d entraînement généré à partir d une évaluation
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS programmes
(
    programme_id  INTEGER GENERATED BY DEFAULT AS IDENTITY,
    evaluation_id INTEGER NOT NULL,
    weeks         INTEGER NOT NULL,
    frequency     INTEGER NOT NULL,
    duration      INTEGER,
    start_date    DATE NOT NULL,
    end_date      DATE NOT NULL,
    snatch_goal   INTEGER,
    cj_goal       INTEGER,
    CONSTRAINT pk_programmes PRIMARY KEY (programme_id),
    CONSTRAINT chk_programmes_1 CHECK (weeks > 0),
    CONSTRAINT chk_programmes_2 CHECK (frequency BETWEEN 3 AND 5),
    CONSTRAINT chk_programmes_3 CHECK (duration BETWEEN 90 AND 150),
    CONSTRAINT chk_programmes_4 CHECK (end_date >= start_date),
    CONSTRAINT chk_programmes_5 CHECK (snatch_goal > 0),
    CONSTRAINT chk_programmes_6 CHECK (cj_goal > 0),
    CONSTRAINT fk_programmes_1 FOREIGN KEY (evaluation_id) REFERENCES eval_summaries (evaluation_id)
);

COMMENT ON TABLE programmes IS 'Programme d entraînement généré pour un athlète';
COMMENT ON COLUMN programmes.weeks IS 'Nombre de semaines du programme: 8, 12, 16';
COMMENT ON COLUMN programmes.frequency IS 'Nombre de séances par semaine: 3, 4, 5';
COMMENT ON COLUMN programmes.duration IS 'Durée d''une séance en minutes : 90, 120, 150';
COMMENT ON COLUMN programmes.start_date IS 'Date de début du programme';
COMMENT ON COLUMN programmes.end_date IS 'Date de fin du programme';
COMMENT ON COLUMN programmes.snatch_goal IS 'Objectif arraché en kg';
COMMENT ON COLUMN programmes.cj_goal IS 'Objectif épaulé-jeté en kg';

CREATE INDEX IF NOT EXISTS idx_programmes_1 ON programmes (evaluation_id);

-- ------------------------------------------------------------
-- PROG_WEEK
-- Semaine d entraînement dans un programme
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS programme_weeks
(
    programme_week_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    programme_id      INTEGER NOT NULL,
    week_number       INTEGER NOT NULL,
    start_date        DATE NOT NULL,
    end_date          DATE NOT NULL,
    week_type         VARCHAR(50) NOT NULL,
    base_percent      NUMERIC(1,2) NOT NULL,
    snatch_goal       INTEGER NOT NULL,
    cj_goal           INTEGER NOT NULL,
    back_squat_goal   INTEGER NOT NULL,
    front_squat_goal  INTEGER NOT NULL,
    snatch_pull_goal  INTEGER NOT NULL,
    cj_pull_goal      INTEGER NOT NULL,
    CONSTRAINT pk_programme_weeks PRIMARY KEY (programme_week_id),
    CONSTRAINT uq_programme_weeks_1 UNIQUE (programme_id, week_number),
    CONSTRAINT chk_programme_weeks_1 CHECK (week_number BETWEEN 1 AND 16),
    CONSTRAINT chk_programme_weeks_2 CHECK (base_percent > 0),
    CONSTRAINT chk_programme_weeks_3 CHECK (end_date >= start_date),
    CONSTRAINT chk_programme_weeks_4 CHECK (week_type IN ('VOLUME', 'TECH', 'STRENGTH', 'PEAK', 'DELOAD')),
    CONSTRAINT fk_programme_weeks_1 FOREIGN KEY (programme_id) REFERENCES programmes (programme_id)
);

COMMENT ON TABLE programme_weeks IS 'Découpage hebdomadaire d''un programme';
COMMENT ON COLUMN programme_weeks.week_type IS 'Type de semaine : VOLUME (F), TECH (T), STRENGTH (S), PEAK (A), DELOAD (D)';
COMMENT ON COLUMN programme_weeks.base_percent IS 'Pourcentage de l''objectif final';
COMMENT ON COLUMN programme_weeks.snatch_goal IS 'Base pour l''arraché';
COMMENT ON COLUMN programme_weeks.cj_goal IS 'Base pour l''épaulé-jeté';
COMMENT ON COLUMN programme_weeks.back_squat_goal IS 'Base pour le squat nuque';
COMMENT ON COLUMN programme_weeks.front_squat_goal IS 'Base pour les squat clavicule';
COMMENT ON COLUMN programme_weeks.snatch_pull_goal IS 'Base pour les tirages d''arraché';
COMMENT ON COLUMN programme_weeks.cj_pull_goal IS 'Base pour les tirages d''épaulé';

CREATE INDEX IF NOT EXISTS idx_programme_weeks_1 ON programme_weeks (programme_id);

-- ------------------------------------------------------------
-- PROG_TRAINING
-- Exercice planifié dans une séance hebdomadaire
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS programme_trainings
(
    programme_training_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    programme_week_id     INTEGER NOT NULL,
    training_number       INTEGER NOT NULL,
    exercice_order        INTEGER NOT NULL,
    exercice_code         VARCHAR(50) NOT NULL,
    set_number            INTEGER NOT NULL,
    rep_number            INTEGER NOT NULL,
    rep_label             VARCHAR(20),
    min_weight            NUMERIC(6, 2),
    max_weight            NUMERIC(6, 2),
    CONSTRAINT pk_programme_trainings PRIMARY KEY (programme_training_id),
    CONSTRAINT chk_programme_trainings_1 CHECK (exercice_order > 0),
    CONSTRAINT chk_programme_trainings_2 CHECK (set_number > 0),
    CONSTRAINT chk_programme_trainings_3 CHECK (rep_number > 0),
    CONSTRAINT chk_programme_trainings_4 CHECK (max_weight IS NULL OR max_weight >= min_weight),
    CONSTRAINT chk_programme_trainings_5 CHECK (training_number BETWEEN 1 AND 5),
    CONSTRAINT fk_programme_trainings_1 FOREIGN KEY (programme_week_id) REFERENCES programme_weeks (programme_week_id)
);

COMMENT ON TABLE programme_trainings IS 'Exercices planifiés dans une semaine de programme';
COMMENT ON COLUMN programme_trainings.training_number IS 'Numéro de la séance hebdomadaire';
COMMENT ON COLUMN programme_trainings.exercice_order IS 'Ordre de l''exercice dans la séance (si plusieurs fois le même ordre => "Au choix")';
COMMENT ON COLUMN programme_trainings.exercice_code IS 'Code unique identifiant l''exercice (voir libellé dans les fichiers i18n)';
COMMENT ON COLUMN programme_trainings.set_number IS 'Nombre de séries';
COMMENT ON COLUMN programme_trainings.rep_number IS 'Nombre de répétitions par série';
COMMENT ON COLUMN programme_trainings.rep_label IS 'Label des répétitions (si complexe, ex : "30s + 10 reps")';
COMMENT ON COLUMN programme_trainings.min_weight IS 'Charge minimale en kg';
COMMENT ON COLUMN programme_trainings.max_weight IS 'Charge maximale en kg';

CREATE INDEX IF NOT EXISTS idx_programme_trainings_1 ON programme_trainings (programme_week_id);

-- ------------------------------------------------------------
-- REF_TIMELINE
-- Table de référence des timelines par archétype et durée
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ref_timelines
(
    ref_timeline_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    archetype       VARCHAR(10)  NOT NULL,
    weeks           INTEGER      NOT NULL,
    timeline        VARCHAR(255) NOT NULL,
    CONSTRAINT pk_ref_timelines PRIMARY KEY (ref_timeline_id),
    CONSTRAINT uq_ref_timelines_1 UNIQUE (archetype, weeks),
    CONSTRAINT chk_ref_timelines_1 CHECK (archetype IN ('MID', 'ROUGH', 'TECH', 'CYCLE', 'LEARN')),
    CONSTRAINT chk_ref_timelines_2 CHECK (weeks IN (8, 12, 16))
);

COMMENT ON TABLE ref_timelines IS 'Timelines de référence par archétype et durée de programme';
COMMENT ON COLUMN ref_timelines.archetype IS 'Archétype de l''athlète : MID, ROUGH, TECH, CYCLE, LEARN';
COMMENT ON COLUMN ref_timelines.weeks IS 'Nombre de semaines du programme : 8, 12, 16';
COMMENT ON COLUMN ref_timelines.timeline IS 'Séquence de types de semaines : VOLUME (F), TECH (T), STRENGTH (S), PEAK (A), DELOAD (D)';

-- ------------------------------------------------------------
-- REF_PLANNING
-- Planification de référence par timeline et semaine
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ref_plannings
(
    ref_planning_id    BIGINT GENERATED ALWAYS AS IDENTITY,
    archetype          VARCHAR(10)  NOT NULL,
    week_type          VARCHAR(50)  NOT NULL,
    day_of_week        INTEGER      NOT NULL,
    exercice_order     INTEGER      NOT NULL,
    categorie_exercice VARCHAR(100) NOT NULL,
    type_exercice      VARCHAR(100),
    strength_weakness  VARCHAR(10),
    set_number         INTEGER,
    rep_number         INTEGER,
    rep_label          VARCHAR(20),
    CONSTRAINT pk_ref_plannings PRIMARY KEY (ref_planning_id),
    CONSTRAINT chk_ref_plannings_1 CHECK (day_of_week BETWEEN 1 AND 5),
    CONSTRAINT chk_ref_plannings_2 CHECK (exercice_order > 0),
    CONSTRAINT chk_ref_plannings_3 CHECK (set_number > 0),
    CONSTRAINT chk_ref_plannings_4 CHECK (rep_number > 0),
    CONSTRAINT chk_ref_plannings_5 CHECK (strength_weakness IN ('STRENGTH', 'WEAKNESS', NULL)),
    CONSTRAINT chk_ref_plannings_6 CHECK (week_type IN ('F', 'T', 'S', 'A', 'D'))
);

COMMENT ON TABLE ref_plannings IS 'Planning de référence associé à une timeline';
COMMENT ON COLUMN ref_plannings.week_type IS 'Type de semaine : VOLUME (F), TECH (T), STRENGTH (S), PEAK (A), DELOAD (D)';
COMMENT ON COLUMN ref_plannings.day_of_week IS 'Numéro de la séance dans la semaine';
COMMENT ON COLUMN ref_plannings.exercice_order IS 'Ordre de passage dans la séance, si plusieurs => "Au choix"';
COMMENT ON COLUMN ref_plannings.categorie_exercice IS 'Catégorie d''exercice attendue';
COMMENT ON COLUMN ref_plannings.type_exercice IS 'Type d''exercice attendu';
COMMENT ON COLUMN ref_plannings.strength_weakness IS 'STRENGTH = point fort, WEAKNESS = point faible';
COMMENT ON COLUMN ref_plannings.set_number IS 'Nombre de séries de référence';
COMMENT ON COLUMN ref_plannings.rep_number IS 'Nombre de répétitions de référence';
COMMENT ON COLUMN ref_plannings.rep_label IS 'Label des répétitions de référence';

-- ------------------------------------------------------------
-- REF_SQUAT
-- Planification de référence des exercices de squat par timeline et semaine
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ref_squats
(
    ref_squat_id    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    goal            VARCHAR(10)  NOT NULL,
    archetype       VARCHAR(10)  NOT NULL,
    week_type       VARCHAR(50) NOT NULL,
    training_number INTEGER     NOT NULL,
    squat_type      VARCHAR(50) NOT NULL,
    exercice_code   VARCHAR(50) NOT NULL,
    set_number      INTEGER     NOT NULL,
    rep_number      INTEGER     NOT NULL,
    rep_label       VARCHAR(20),
    estimate_value  NUMERIC(1, 2),
    CONSTRAINT pk_ref_squats PRIMARY KEY (ref_squat_id),
    CONSTRAINT chk_ref_squats_1 CHECK (week_type IN ('F', 'T', 'S', 'A', 'D')),
    CONSTRAINT chk_ref_squats_2 CHECK (training_number BETWEEN 1 AND 3),
    CONSTRAINT chk_ref_squats_3 CHECK (set_number > 0),
    CONSTRAINT chk_ref_squats_4 CHECK (rep_number > 0),
    CONSTRAINT chk_ref_squats_5 CHECK (goal IN ('STRENGTH', 'SPEED', 'KEEP')),
    CONSTRAINT chk_ref_squats_6 CHECK (archetype IN ('MID', 'ROUGH', 'TECH', 'CYCLE', 'LEARN'))
);

COMMENT ON TABLE ref_squats IS 'Exercices de squat de référence associés à une timeline';
COMMENT ON COLUMN ref_squats.goal IS 'Objectif : STRENGTH = Force, SPEED = Vitesse, KEEP = maintien';
COMMENT ON COLUMN ref_squats.archetype IS 'Archétype de l''athlète : MID, ROUGH, TECH, CYCLE, LEARN';
COMMENT ON COLUMN ref_squats.week_type IS 'Type de semaine : VOLUME (F), TECH (T), STRENGTH (S), PEAK (A), DELOAD (D)';
COMMENT ON COLUMN ref_squats.training_number IS 'Numéro de la séance dans la semaine';
COMMENT ON COLUMN ref_squats.squat_type IS 'Type de squat : BACK, FRONT';
COMMENT ON COLUMN ref_squats.exercice_code IS 'Code unique identifiant l''exercice (voir libellé dans les fichiers i18n)';
COMMENT ON COLUMN ref_squats.set_number IS 'Nombre de séries de référence';
COMMENT ON COLUMN ref_squats.rep_number IS 'Nombre de répétitions de référence';
COMMENT ON COLUMN ref_squats.rep_label IS 'Label des répétitions (si complexe, ex : "30s + 10 reps")';
COMMENT ON COLUMN ref_squats.estimate_value IS 'Pourcentage de charge estimée par rapport à l''objectif de squat';

-- ------------------------------------------------------------
-- REF_PULL
-- Planification de référence des exercices de tirage par timeline et semaine
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ref_pulls
(
    ref_pull_id     INTEGER GENERATED BY DEFAULT AS IDENTITY,
    goal            VARCHAR(10)  NOT NULL,
    archetype       VARCHAR(10)  NOT NULL,
    week_type       VARCHAR(50) NOT NULL,
    training_number INTEGER     NOT NULL,
    pull_type       VARCHAR(50) NOT NULL,
    exercice_code   VARCHAR(50) NOT NULL,
    set_number      INTEGER     NOT NULL,
    rep_number      INTEGER     NOT NULL,
    rep_label       VARCHAR(20),
    estimate_value  NUMERIC(1, 2),
    CONSTRAINT pk_ref_pulls PRIMARY KEY (ref_pull_id),
    CONSTRAINT chk_ref_pulls_1 CHECK (week_type IN ('F', 'T', 'S', 'A', 'D')),
    CONSTRAINT chk_ref_pulls_2 CHECK (training_number BETWEEN 1 AND 3),
    CONSTRAINT chk_ref_pulls_3 CHECK (set_number > 0),
    CONSTRAINT chk_ref_pulls_4 CHECK (rep_number > 0),
    CONSTRAINT chk_ref_pulls_5 CHECK (goal IN ('STRENGTH', 'SPEED', 'KEEP')),
    CONSTRAINT chk_ref_pulls_6 CHECK (archetype IN ('MID', 'ROUGH', 'TECH', 'CYCLE', 'LEARN'))
);

COMMENT ON TABLE ref_pulls IS 'Exercices de tirage de référence associés à une timeline';
COMMENT ON COLUMN ref_pulls.goal IS 'Objectif : STRENGTH = Force, SPEED = Vitesse, KEEP = maintien';
COMMENT ON COLUMN ref_pulls.archetype IS 'Archétype de l''athlète : MID, ROUGH, TECH, CYCLE, LEARN';
COMMENT ON COLUMN ref_pulls.week_type IS 'Type de semaine : VOLUME (F), TECH (T), STRENGTH (S), PEAK (A), DELOAD (D)';
COMMENT ON COLUMN ref_pulls.training_number IS 'Numéro de la séance dans la semaine';
COMMENT ON COLUMN ref_pulls.pull_type IS 'Type de tirage : SNATCH_PULL, CJ_PULL, etc.';
COMMENT ON COLUMN ref_pulls.exercice_code IS 'Code unique identifiant l''exercice (voir libellé dans les fichiers i18n)';
COMMENT ON COLUMN ref_pulls.set_number IS 'Nombre de séries de référence';
COMMENT ON COLUMN ref_pulls.rep_number IS 'Nombre de répétitions de référence';
COMMENT ON COLUMN ref_pulls.rep_label IS 'Label des répétitions (si complexe, ex : "30s + 10 reps")';
COMMENT ON COLUMN ref_pulls.estimate_value IS 'Pourcentage de charge estimée par rapport à l''objectif de tirage';



-- ============================================================
-- DATA — EXERCICES
-- IDs assignés manuellement (GENERATED BY DEFAULT)
-- exercice_code = clé complète i18n (exercice.snatch.tech.simple, etc.)
-- exercice_ref = ID de l'exercice parent
-- estimate_value = % de charge par rapport à l'exercice de référence
-- ============================================================

-- Exercice Racine
INSERT INTO exercices (exercice_id, type_exercice, categorie_exercice, exercice_code, exercice_ref, estimate_value) VALUES
(1, 'SNATCH', 'TECH', 'exercice.total', NULL, NULL);

-- ============================================================
-- ARRACHÉ (ref = total ID 1, estimate = 0.44)
-- ============================================================

-- Tech
INSERT INTO exercices (exercice_id, type_exercice, categorie_exercice, exercice_code, exercice_ref, estimate_value) VALUES
(2,  'SNATCH', 'TECH', 'exercice.snatch.tech.simple', 1, 0.44),
(3,  'SNATCH', 'TECH', 'exercice.snatch.tech.double', 2, 0.95),
(4,  'SNATCH', 'TECH', 'exercice.snatch.tech.triple', 2, 0.90);

-- Combinés
INSERT INTO exercices (exercice_id, type_exercice, categorie_exercice, exercice_code, exercice_ref, estimate_value) VALUES
(5,  'SNATCH', 'COMBI', 'exercice.snatch.complex.complex-1',  2, 0.80),
(6,  'SNATCH', 'COMBI', 'exercice.snatch.complex.complex-2',  2, 0.80),
(7,  'SNATCH', 'COMBI', 'exercice.snatch.complex.complex-3',  2, 0.75),
(8,  'SNATCH', 'COMBI', 'exercice.snatch.complex.complex-4',  2, 0.80),
(9,  'SNATCH', 'COMBI', 'exercice.snatch.complex.complex-5',  2, 0.80),
(10, 'SNATCH', 'COMBI', 'exercice.snatch.complex.complex-6',  2, 0.85),
(11, 'SNATCH', 'COMBI', 'exercice.snatch.complex.complex-7',  2, 0.85),
(12, 'SNATCH', 'COMBI', 'exercice.snatch.complex.complex-8',  2, 0.75),
(13, 'SNATCH', 'COMBI', 'exercice.snatch.complex.complex-9',  2, 0.60),
(14, 'SNATCH', 'COMBI', 'exercice.snatch.complex.complex-10', 2, 0.80),
(15, 'SNATCH', 'COMBI', 'exercice.snatch.complex.complex-11', 2, 0.80);

-- Semi-technique lourd (heavy)
INSERT INTO exercices (exercice_id, type_exercice, categorie_exercice, exercice_code, exercice_ref, estimate_value) VALUES
(16, 'SNATCH', 'SEMI_LOURD', 'exercice.snatch.heavy.squat',               2, 1.00),
(17, 'SNATCH', 'SEMI_LOURD', 'exercice.snatch.heavy.power',               2, 0.85),
(18, 'SNATCH', 'SEMI_LOURD', 'exercice.snatch.heavy.block',               2, 0.95),
(19, 'SNATCH', 'SEMI_LOURD', 'exercice.snatch.heavy.hang',                2, 0.95),
(20, 'SNATCH', 'SEMI_LOURD', 'exercice.snatch.heavy.no-feet',             2, 0.92),
(21, 'SNATCH', 'SEMI_LOURD', 'exercice.snatch.heavy.balance',              2, 1.00),
(22, 'SNATCH', 'SEMI_LOURD', 'exercice.snatch.heavy.pause',               2, 0.80),
(23, 'SNATCH', 'SEMI_LOURD', 'exercice.snatch.heavy.hip',                 2, 0.90),
(24, 'SNATCH', 'SEMI_LOURD', 'exercice.snatch.heavy.deficit',             2, 0.95),
(25, 'SNATCH', 'SEMI_LOURD', 'exercice.snatch.heavy.slow-start',          2, 0.85),
(26, 'SNATCH', 'SEMI_LOURD', 'exercice.snatch.heavy.block-power',         2, 0.80),
(27, 'SNATCH', 'SEMI_LOURD', 'exercice.snatch.heavy.squat-pause', 2, 0.95),
(28, 'SNATCH', 'SEMI_LOURD', 'exercice.snatch.heavy.hang-low',            2, 0.95),
(29, 'SNATCH', 'SEMI_LOURD', 'exercice.snatch.heavy.hang-high',           2, 0.95),
(30, 'SNATCH', 'SEMI_LOURD', 'exercice.snatch.heavy.no-feet-hip',         2, 0.85),
(31, 'SNATCH', 'SEMI_LOURD', 'exercice.snatch.heavy.no-feet-hang',        2, 0.80),
(32, 'SNATCH', 'SEMI_LOURD', 'exercice.snatch.heavy.hang-power',          2, 0.80);

-- Semi-technique léger (light)
INSERT INTO exercices (exercice_id, type_exercice, categorie_exercice, exercice_code, exercice_ref, estimate_value) VALUES
(33, 'SNATCH', 'SEMI_LEGER', 'exercice.snatch.light.muscle',               2, 0.66),
(34, 'SNATCH', 'SEMI_LEGER', 'exercice.snatch.light.tall',          2, 0.56),
(35, 'SNATCH', 'SEMI_LEGER', 'exercice.snatch.light.drop',               2, 0.56),
(37, 'SNATCH', 'SEMI_LEGER', 'exercice.snatch.light.muscle-hang',          2, 0.63),
(38, 'SNATCH', 'SEMI_LEGER', 'exercice.snatch.light.muscle-block',         2, 0.63),
(39, 'SNATCH', 'SEMI_LEGER', 'exercice.snatch.light.muscle-no-contact',    2, 0.63),
(40, 'SNATCH', 'SEMI_LEGER', 'exercice.snatch.light.no-feet-power-hip',   2, 0.70),
(41, 'SNATCH', 'SEMI_LEGER', 'exercice.snatch.light.muscle-clean-grip',    2, 0.60),
(42, 'SNATCH', 'SEMI_LEGER', 'exercice.snatch.light.hip-power',           2, 0.75);

-- Tirages arraché (pull)
INSERT INTO exercices (exercice_id, type_exercice, categorie_exercice, exercice_code, exercice_ref, estimate_value) VALUES
(44, 'PULL', 'TECH', 'exercice.snatch.pull.simple',    2, 1.20),
(45, 'PULL', 'TECH', 'exercice.snatch.pull.double',    44, 0.95),
(46, 'PULL', 'TECH', 'exercice.snatch.pull.triple',    44, 0.90),
(47, 'PULL', 'TECH', 'exercice.snatch.pull.high',      2, 1.00),
(48, 'PULL', 'TECH', 'exercice.snatch.pull.high-hang', 47, 0.95),
(49, 'PULL', 'TECH', 'exercice.snatch.pull.block',     44, NULL),
(50, 'PULL', 'TECH', 'exercice.snatch.pull.deficit',   44, NULL),
(51, 'PULL', 'TECH', 'exercice.snatch.pull.pause',     44, NULL),
(52, 'PULL', 'TECH', 'exercice.snatch.pull.hip',       44, NULL),
(53, 'PULL', 'TECH', 'exercice.snatch.pull.tng',       44, NULL);

-- Renforcement spécifique arraché (renfo)
INSERT INTO exercices (exercice_id, type_exercice, categorie_exercice, exercice_code, exercice_ref, estimate_value) VALUES
(54, 'SNATCH', 'RENFO', 'exercice.snatch.renfo.sots-press',    2, 0.45),
(55, 'SNATCH', 'RENFO', 'exercice.snatch.renfo.squat-elastic',    2, 0.60),
(56, 'SNATCH', 'RENFO', 'exercice.snatch.renfo.pull-arm',           2, 0.45),
(57, 'SNATCH', 'RENFO', 'exercice.snatch.renfo.row',                2, 0.55),
(58, 'SNATCH', 'RENFO', 'exercice.snatch.renfo.strict-press',      2, 0.50),
(59, 'SNATCH', 'RENFO', 'exercice.snatch.renfo.tall-no-feet', 2, 0.40);

-- ============================================================
-- ÉPAULÉ (ref = total ID 1, estimate = 0.56)
-- ============================================================

-- Tech
INSERT INTO exercices (exercice_id, type_exercice, categorie_exercice, exercice_code, exercice_ref, estimate_value) VALUES
(60, 'CLEAN', 'TECH', 'exercice.clean.tech.simple', 1, 0.56),
(61, 'CLEAN', 'TECH', 'exercice.clean.tech.double', 60, 0.95),
(62, 'CLEAN', 'TECH', 'exercice.clean.tech.triple', 60, 0.90);

-- Combinés
INSERT INTO exercices (exercice_id, type_exercice, categorie_exercice, exercice_code, exercice_ref, estimate_value) VALUES
(63, 'CLEAN', 'COMBI', 'exercice.clean.complex.complex-1', 60, 0.75),
(64, 'CLEAN', 'COMBI', 'exercice.clean.complex.complex-2', 60, 0.80),
(65, 'CLEAN', 'COMBI', 'exercice.clean.complex.complex-3', 60, 0.80),
(66, 'CLEAN', 'COMBI', 'exercice.clean.complex.complex-4', 60, 0.70),
(67, 'CLEAN', 'COMBI', 'exercice.clean.complex.complex-5', 60, 0.75),
(68, 'CLEAN', 'COMBI', 'exercice.clean.complex.complex-6', 60, 0.75),
(69, 'CLEAN', 'COMBI', 'exercice.clean.complex.complex-7', 60, 0.85),
(70, 'CLEAN', 'COMBI', 'exercice.clean.complex.complex-8', 60, 0.80);

-- Semi-technique lourd (heavy)
INSERT INTO exercices (exercice_id, type_exercice, categorie_exercice, exercice_code, exercice_ref, estimate_value) VALUES
(71, 'CLEAN', 'SEMI_LOURD', 'exercice.clean.heavy.squat',          60, 1.00),
(72, 'CLEAN', 'SEMI_LOURD', 'exercice.clean.heavy.power',          60, 0.84),
(73, 'CLEAN', 'SEMI_LOURD', 'exercice.clean.heavy.block',          60, 0.95),
(74, 'CLEAN', 'SEMI_LOURD', 'exercice.clean.heavy.hang',           60, 0.95),
(75, 'CLEAN', 'SEMI_LOURD', 'exercice.clean.heavy.no-feet',        60, 0.92),
(76, 'CLEAN', 'SEMI_LOURD', 'exercice.clean.heavy.pause',          60, 0.90),
(77, 'CLEAN', 'SEMI_LOURD', 'exercice.clean.heavy.hip',            60, 0.90),
(78, 'CLEAN', 'SEMI_LOURD', 'exercice.clean.heavy.deficit',        60, 0.95),
(79, 'CLEAN', 'SEMI_LOURD', 'exercice.clean.heavy.block-power',    60, 0.80),
(80, 'CLEAN', 'SEMI_LOURD', 'exercice.clean.heavy.hang-high',      60, 0.95),
(81, 'CLEAN', 'SEMI_LOURD', 'exercice.clean.heavy.hang-low',       60, 0.95),
(82, 'CLEAN', 'SEMI_LOURD', 'exercice.clean.heavy.hang-power-high', 60, 0.80),
(83, 'CLEAN', 'SEMI_LOURD', 'exercice.clean.heavy.hang-power-low', 60, 0.80),
(84, 'CLEAN', 'SEMI_LOURD', 'exercice.clean.heavy.no-feet-hip',    60, 0.85),
(85, 'CLEAN', 'SEMI_LOURD', 'exercice.clean.heavy.no-feet-power',  60, 0.85);

-- Semi-technique léger (light)
INSERT INTO exercices (exercice_id, type_exercice, categorie_exercice, exercice_code, exercice_ref, estimate_value) VALUES
(86,  'CLEAN', 'SEMI_LEGER', 'exercice.clean.light.muscle',              60, 0.63),
(87,  'CLEAN', 'SEMI_LEGER', 'exercice.clean.light.tall',         60, 0.62),
(88,  'CLEAN', 'SEMI_LEGER', 'exercice.clean.light.hip-power',          60, 0.75),
(89,  'CLEAN', 'SEMI_LEGER', 'exercice.clean.light.no-feet-hang',       60, 0.75),
(90,  'CLEAN', 'SEMI_LEGER', 'exercice.clean.light.no-feet-power-hip',  60, 0.70),
(91,  'CLEAN', 'SEMI_LEGER', 'exercice.clean.light.muscle-hang',         60, 0.60),
(92,  'CLEAN', 'SEMI_LEGER', 'exercice.clean.light.muscle-block',        60, 0.60),
(93,  'CLEAN', 'SEMI_LEGER', 'exercice.clean.light.muscle-no-contact',   60, 0.60),
(94,  'CLEAN', 'SEMI_LEGER', 'exercice.clean.light.muscle-power-hip',    60, 0.70);

-- Tirages épaulé (pull)
INSERT INTO exercices (exercice_id, type_exercice, categorie_exercice, exercice_code, exercice_ref, estimate_value) VALUES
(96,  'PULL', 'TECH', 'exercice.clean.pull.simple',   60, 1.30),
(97,  'PULL', 'TECH', 'exercice.clean.pull.double',   60, 1.24),
(98,  'PULL', 'TECH', 'exercice.clean.pull.triple',   60, 1.17),
(99,  'PULL', 'TECH', 'exercice.clean.pull.hip',      60, NULL),
(100, 'PULL', 'TECH', 'exercice.clean.pull.block',    60, NULL),
(101, 'PULL', 'TECH', 'exercice.clean.pull.deficit', 60, NULL),
(102, 'PULL', 'TECH', 'exercice.clean.pull.pause',    60, NULL),
(103, 'PULL', 'TECH', 'exercice.clean.pull.tng',      60, NULL);

-- Renforcement spécifique épaulé (renfo)
INSERT INTO exercices (exercice_id, type_exercice, categorie_exercice, exercice_code, exercice_ref, estimate_value) VALUES
(104, 'CLEAN', 'RENFO', 'exercice.clean.renfo.pull-arm',           60, 0.45),
(105, 'CLEAN', 'RENFO', 'exercice.clean.renfo.row',                60, 0.50),
(106, 'CLEAN', 'RENFO', 'exercice.clean.renfo.tall-no-feet', 60, 0.40);

-- Squats (ref = épaulé ID 60, ratio vs épaulé)
INSERT INTO exercices (exercice_id, type_exercice, categorie_exercice, exercice_code, exercice_ref, estimate_value) VALUES
(107, 'SQUAT', 'BACK', 'exercice.squat.back.simple',          60, 1.35),
(108, 'SQUAT', 'BACK', 'exercice.squat.back.double',          107, 0.95),
(109, 'SQUAT', 'BACK', 'exercice.squat.back.triple',          107, 0.90),
(110, 'SQUAT', 'BACK', 'exercice.squat.back.pause',           107, 0.85),
(111, 'SQUAT', 'BACK', 'exercice.squat.back.eccentric',       107, 0.80),
(112, 'SQUAT', 'BACK', 'exercice.squat.back.eccentric-pause', 107, 0.80),
(113, 'SQUAT', 'BACK', 'exercice.squat.back.jump',            107, 0.35),

(114, 'SQUAT', 'FRONT', 'exercice.squat.front.anderson',        115, 0.85),
(115, 'SQUAT', 'FRONT', 'exercice.squat.front.simple',         60, 1.14),
(116, 'SQUAT', 'FRONT', 'exercice.squat.front.double',         115, 0.95),
(117, 'SQUAT', 'FRONT', 'exercice.squat.front.triple',         115, 0.90),
(118, 'SQUAT', 'FRONT', 'exercice.squat.front.pause',          115, 0.85),
(119, 'SQUAT', 'FRONT', 'exercice.squat.front.plus-back',      115, NULL);

-- ============================================================
-- JETÉ (ref = total ID 1, estimate = 0.56)
-- ============================================================

-- Tech
INSERT INTO exercices (exercice_id, type_exercice, categorie_exercice, exercice_code, exercice_ref, estimate_value) VALUES
(120, 'JERK', 'TECH', 'exercice.jerk.tech.simple', 1, 0.56);

-- Combinés
INSERT INTO exercices (exercice_id, type_exercice, categorie_exercice, exercice_code, exercice_ref, estimate_value) VALUES
(121, 'JERK', 'COMBI', 'exercice.jerk.complex.complex-1', 120, 0.80),
(122, 'JERK', 'COMBI', 'exercice.jerk.complex.complex-2', 120, 0.80),
(123, 'JERK', 'COMBI', 'exercice.jerk.complex.complex-3', 120, 0.65),
(124, 'JERK', 'COMBI', 'exercice.jerk.complex.complex-4', 120, 0.65);

-- Semi-technique lourd (heavy)
INSERT INTO exercices (exercice_id, type_exercice, categorie_exercice, exercice_code, exercice_ref, estimate_value) VALUES
(125, 'JERK', 'SEMI_LOURD', 'exercice.jerk.heavy.power',   120, 0.92),
(126, 'JERK', 'SEMI_LOURD', 'exercice.jerk.heavy.no-feet', 120, 0.90),
(127, 'JERK', 'SEMI_LOURD', 'exercice.jerk.heavy.pause',   120, 0.90);

-- Semi-technique léger (light)
INSERT INTO exercices (exercice_id, type_exercice, categorie_exercice, exercice_code, exercice_ref, estimate_value) VALUES
(128, 'JERK', 'SEMI_LEGER', 'exercice.jerk.light.muscle',       120, 0.71),
(129, 'JERK', 'SEMI_LEGER', 'exercice.jerk.light.va-et-vient', 120, 0.60),
(130, 'JERK', 'SEMI_LEGER', 'exercice.jerk.light.split-call',  120, 0.70),
(131, 'JERK', 'SEMI_LEGER', 'exercice.jerk.light.drop',        120, 0.50);

-- Renforcement spécifique jeté (renfo)
INSERT INTO exercices (exercice_id, type_exercice, categorie_exercice, exercice_code, exercice_ref, estimate_value) VALUES
(132, 'JERK', 'RENFO', 'exercice.jerk.renfo.develop-split',          120, 0.55),
(133, 'JERK', 'RENFO', 'exercice.jerk.renfo.split-bar',              120, 0.70),
(134, 'JERK', 'RENFO', 'exercice.jerk.renfo.military-press',         120, 0.58),
(135, 'JERK', 'RENFO', 'exercice.jerk.renfo.military-press-elastic', 120, NULL),
(136, 'JERK', 'RENFO', 'exercice.jerk.renfo.neck-press',             120, 0.50),
(137, 'JERK', 'RENFO', 'exercice.jerk.renfo.call',                   120, 1.20),
(138, 'JERK', 'RENFO', 'exercice.jerk.renfo.bar-hold',               120, NULL),
(139, 'JERK', 'RENFO', 'exercice.jerk.renfo.bar-hold-renfo',         120, NULL);

-- ============================================================
-- MUSCULATION (pas de parent)
-- ============================================================
INSERT INTO exercices (exercice_id, type_exercice, categorie_exercice, exercice_code, exercice_ref, estimate_value) VALUES
-- Général
(140, 'MUSCU', 'GEN',   'exercice.muscu.rdl-romanian',               NULL, NULL),
(141, 'MUSCU', 'GEN',   'exercice.muscu.pull-ups',                   NULL, NULL),
(142, 'MUSCU', 'GEN',   'exercice.muscu.push-ups',                   NULL, NULL),
(143, 'MUSCU', 'GEN',   'exercice.muscu.lateral-raises',             NULL, NULL),
(144, 'MUSCU', 'GEN',   'exercice.muscu.bench-row',                  NULL, NULL),
(145, 'MUSCU', 'GEN',   'exercice.muscu.bosu-cj-pull',               NULL, NULL),
(146, 'MUSCU', 'GEN',   'exercice.muscu.neck-pull-ups',              NULL, NULL),
(147, 'MUSCU', 'GEN',   'exercice.muscu.bird-row',                   NULL, NULL),
(148, 'MUSCU', 'GEN',   'exercice.muscu.pull-over',                  NULL, NULL),
-- Jambes
(149, 'MUSCU', 'LEG',   'exercice.muscu.lunge-bulgarian',            NULL, NULL),
(150, 'MUSCU', 'LEG',   'exercice.muscu.lunge-walking',              NULL, NULL),
(151, 'MUSCU', 'LEG',   'exercice.muscu.lunge-box',                  NULL, NULL),
(152, 'MUSCU', 'LEG',   'exercice.muscu.leg-extension-unilateral',   NULL, NULL),
(153, 'MUSCU', 'LEG',   'exercice.muscu.leg-extension',              NULL, NULL),
(154, 'MUSCU', 'LEG',   'exercice.muscu.sled-push',                  NULL, NULL),
(155, 'MUSCU', 'LEG',   'exercice.muscu.goblet-squat',               NULL, NULL),
(156, 'MUSCU', 'LEG',   'exercice.muscu.pistol-squat',               NULL, NULL),
(157, 'MUSCU', 'LEG',   'exercice.muscu.sled-pull',                  NULL, NULL),
-- Chaîne postérieure
(158, 'MUSCU', 'POST',  'exercice.muscu.rdl-unilateral',             NULL, NULL),
(159, 'MUSCU', 'POST',  'exercice.muscu.single-leg-glute-bridge',    NULL, NULL),
(160, 'MUSCU', 'POST',  'exercice.muscu.nordic-curl',                NULL, NULL),
(161, 'MUSCU', 'POST',  'exercice.muscu.lower-back-prone',           NULL, NULL),
(162, 'MUSCU', 'POST',  'exercice.muscu.superman',                   NULL, NULL),
(163, 'MUSCU', 'POST',  'exercice.muscu.bent-over-row',              NULL, NULL),
(164, 'MUSCU', 'POST',  'exercice.muscu.australian-row',             NULL, NULL),
(165, 'MUSCU', 'POST',  'exercice.muscu.lumberjack-row',             NULL, NULL),
(166, 'MUSCU', 'POST',  'exercice.muscu.leg-curl-swissball',         NULL, NULL),
(167, 'MUSCU', 'POST',  'exercice.muscu.leg-curl-elastic-unilateral', NULL, NULL),
(168, 'MUSCU', 'POST',  'exercice.muscu.hip-thrust-bar',             NULL, NULL),
(169, 'MUSCU', 'POST',  'exercice.muscu.hip-extension-elastic',      NULL, NULL),
(170, 'MUSCU', 'POST',  'exercice.muscu.kettlebell-swing',           NULL, NULL),
(171, 'MUSCU', 'POST',  'exercice.muscu.good-morning',               NULL, NULL),
-- Core / Gainage
(172, 'MUSCU', 'CORE',  'exercice.muscu.weighted-plank',             NULL, NULL),
(173, 'MUSCU', 'CORE',  'exercice.muscu.dynamic-plank',              NULL, NULL),
(174, 'MUSCU', 'CORE',  'exercice.muscu.swissball-plank',            NULL, NULL),
(175, 'MUSCU', 'CORE',  'exercice.muscu.obliques-elastic',           NULL, NULL),
(176, 'MUSCU', 'CORE',  'exercice.muscu.obliques-bar',               NULL, NULL),
(177, 'MUSCU', 'CORE',  'exercice.muscu.russian-twist',              NULL, NULL),
(178, 'MUSCU', 'CORE',  'exercice.muscu.bar-plank',                  NULL, NULL),
(179, 'MUSCU', 'CORE',  'exercice.muscu.inclined-plank',             NULL, NULL),
(180, 'MUSCU', 'CORE',  'exercice.muscu.snatch-squat-elastic-muscu', NULL, NULL),
-- Plyométrie / Cardio
(181, 'MUSCU', 'PLYO',  'exercice.muscu.box-jump',                   NULL, NULL),
(182, 'MUSCU', 'CARDIO','exercice.muscu.cardio-plyo',                NULL, NULL);

-- ============================================================
-- DATA — CORRECTIONS
-- ============================================================

INSERT INTO corrections (exercice_id, correction_id) VALUES
-- Arraché flexion (ID 16) → correctifs
(16, 5),    -- Combiné 1
(16, 6),    -- Combiné 2
(16, 22),   -- Arraché Pause
(16, 21),   -- Chute Arraché
(16, 16),   -- Arraché Flexion
(16, 35),   -- Chute Arraché sans élan
(16, 34),   -- Passage Arraché
(16, 54),   -- Développé Arraché Flexion
(16, 55),   -- Flexion Arraché avec Élastique

-- Arraché debout (ID 17) → correctifs
(17, 7),    -- Combiné 3
(17, 8),    -- Combiné 4
(17, 18),   -- Arraché Plot
(17, 25),   -- Arraché Départ Lent
(17, 17),   -- Arraché Debout
(17, 41),   -- Arraché Force Prise Épaulé
(17, 42),   -- Arraché Debout Bassin
(17, 56),   -- Tirage Bras Arraché
(17, 58),   -- Développé Arraché Debout

-- Arraché plots (ID 18) → correctifs
(18, 9),    -- Combiné 5
(18, 10),   -- Combiné 6
(18, 19),   -- Arraché Suspension
(18, 24),   -- Arraché Déficit
(18, 18),   -- Arraché Plots
(18, 38),   -- Arraché Force Plots
(18, 40),   -- Arraché Puissance Debout Bassin
(18, 57),   -- Rowing Prise Arraché
(18, 56),   -- Tirage Bras Arraché

-- Arraché suspension (ID 19) → correctifs
(19, 9),    -- Combiné 5
(19, 10),   -- Combiné 6
(19, 18),   -- Arraché Plots
(19, 24),   -- Arraché Déficit
(19, 19),   -- Arraché Suspension
(19, 37),   -- Arraché Force Suspension
(19, 40),   -- Arraché Puissance Debout Bassin
(19, 57),   -- Rowing Prise Arraché
(19, 56),   -- Tirage Bras Arraché

-- Arraché puissance (ID 20) → correctifs
(20, 11),   -- Combiné 7
(20, 12),   -- Combiné 8
(20, 30),   -- Arraché Puissance Bassin
(20, 25),   -- Arraché Départ Lent
(20, 20),   -- Arraché Puissance
(20, 33),   -- Arraché Force
(20, 34),   -- Passage Arraché
(20, 59),   -- Passage Arraché Pied Plat
(20, 57),   -- Rowing Prise Arraché

-- Arraché force (ID 33) → correctifs
(33, 7),    -- Combiné 3
(33, 13),   -- Combiné 9
(33, 26),   -- Arraché Debout Plot
(33, 20),   -- Arraché Puissance
(33, 39),   -- Arraché Force sans contact
(33, 40),   -- Arraché Puissance Debout Bassin
(33, 33),   -- Arraché Force
(33, 57),   -- Rowing Prise Arraché
(33, 56),   -- Tirage Bras Arraché

-- Chute arraché (ID 21) → correctifs
(21, 13),   -- Combiné 9
(21, 6),    -- Combiné 2
(21, 23),   -- Arraché Bassin
(21, 27),   -- Arraché Flexion pause réception
(21, 21),   -- Chute Arraché
(21, 35),   -- Chute Arraché sans élan
(21, 34),   -- Passage Arraché
(21, 54),   -- Développé Arraché Flexion
(21, 55),   -- Flexion Arraché avec Élastique

-- Passage arraché (ID 34) → correctifs
(34, 14),   -- Combiné 10
(34, 15),   -- Combiné 11
(34, 23),   -- Arraché Bassin
(34, 19),   -- Arraché Suspension
(34, 35),   -- Chute Arraché sans élan
(34, 37),   -- Arraché Force Suspension
(34, 34),   -- Passage Arraché
(34, 56),   -- Tirage Bras Arraché
(34, 59),   -- Passage Arraché Pied Plat

-- Épaulé flexion (ID 71) → correctifs
(71, 63),   -- Combiné 1
(71, 64),   -- Combiné 2
(71, 76),   -- Épaulé Pause
(71, 77),   -- Épaulé Bassin
(71, 71),   -- Épaulé Flexion
(71, 87),   -- Passage Épaulé
(71, 90),   -- Épaulé Puissance Flexion Bassin
(71, 106),  -- Passage Épaulé Pied Plat
(71, 105),  -- Rowing Prise Épaulé

-- Épaulé debout (ID 72) → correctifs
(72, 65),   -- Combiné 3
(72, 66),   -- Combiné 4
(72, 73),   -- Épaulé Plot
(72, 85),   -- Épaulé Puissance Debout
(72, 72),   -- Épaulé Debout
(72, 88),   -- Épaulé Debout Bassin
(72, 86),   -- Épaulé Force
(72, 104),  -- Tirage Bras Épaulé
(72, 105),  -- Rowing Prise Épaulé

-- Épaulé plots (ID 73) → correctifs
(73, 65),   -- Combiné 3
(73, 67),   -- Combiné 5
(73, 74),   -- Épaulé Suspension
(73, 78),   -- Épaulé Déficit
(73, 73),   -- Épaulé Plots
(73, 92),   -- Épaulé Force Plots
(73, 94),   -- Épaulé Puissance Debout Bassin
(73, 104),  -- Tirage Bras Épaulé
(73, 105),  -- Rowing Prise Épaulé

-- Épaulé suspension (ID 74) → correctifs
(74, 65),   -- Combiné 3
(74, 67),   -- Combiné 5
(74, 73),   -- Épaulé Plots
(74, 78),   -- Épaulé Déficit
(74, 74),   -- Épaulé Suspension
(74, 91),   -- Épaulé Force Suspension
(74, 94),   -- Épaulé Puissance Debout Bassin
(74, 104),  -- Tirage Bras Épaulé
(74, 105),  -- Rowing Prise Épaulé

-- Épaulé puissance (ID 75) → correctifs
(75, 68),   -- Combiné 6
(75, 84),   -- Épaulé Puissance Bassin
(75, 76),   -- Épaulé Pause
(75, 75),   -- Épaulé Puissance
(75, 86),   -- Épaulé Force
(75, 87),   -- Passage Épaulé
(75, 106),  -- Passage Épaulé Pied Plat
(75, 105),  -- Rowing Prise Épaulé

-- Épaulé force (ID 86) → correctifs
(86, 65),   -- Combiné 3
(86, 66),   -- Combiné 4
(86, 79),   -- Épaulé Debout Plot
(86, 75),   -- Épaulé Puissance
(86, 93),   -- Épaulé Force sans contact
(86, 94),   -- Épaulé Puissance Debout Bassin
(86, 86),   -- Épaulé Force
(86, 104),  -- Tirage Bras Épaulé
(86, 105),  -- Rowing Prise Épaulé

-- Passage épaulé (ID 87) → correctifs
(87, 69),   -- Combiné 7
(87, 70),   -- Combiné 8
(87, 77),   -- Épaulé Bassin
(87, 74),   -- Épaulé Suspension
(87, 90),   -- Épaulé Puissance Flexion Bassin
(87, 91),   -- Épaulé Force Suspension
(87, 87),   -- Passage Épaulé
(87, 106),  -- Passage Épaulé Pied Plat
(87, 104),  -- Tirage Bras Épaulé

-- Jeté fente (ID 120) → correctifs
(120, 121), -- Combiné 1
(120, 122), -- Combiné 2
(120, 127), -- Jeté Pause
(120, 120), -- Jeté Fente
(120, 129), -- Va-et-viens Jeté
(120, 130), -- Jeté Fente Appel Fente
(120, 131), -- Chute de Jeté
(120, 132), -- Développé Fente
(120, 133), -- Fente à la barre

-- Jeté debout (ID 125) → correctifs
(125, 123), -- Combiné 3
(125, 122), -- Combiné 2
(125, 126), -- Jeté Puissance
(125, 127), -- Jeté Pause
(125, 125), -- Jeté Debout
(125, 128), -- Jeté Force
(125, 136), -- Développé Nuque
(125, 139), -- Appel de Jeté ou Gainage Barre

-- Jeté puissance (ID 126) → correctifs
(126, 122), -- Combiné 2
(126, 123), -- Combiné 3
(126, 125), -- Jeté Debout
(126, 127), -- Jeté Pause
(126, 126), -- Jeté Puissance
(126, 128), -- Jeté Force
(126, 136), -- Développé Nuque
(126, 139), -- Appel de Jeté ou Gainage Barre

-- Jeté force (ID 128) → correctifs
(128, 124), -- Combiné 4
(128, 125), -- Jeté Debout
(128, 127), -- Jeté Pause
(128, 126), -- Jeté Puissance
(128, 128), -- Jeté Force
(128, 134), -- Développé Militaire
(128, 139); -- Appel de Jeté ou Gainage Barre
