-- ------------------------------------------------------------
-- EXERCICE
-- Catalogue des exercices de référence
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS exercices
(
    exercice_id        INTEGER GENERATED BY DEFAULT AS IDENTITY,
    exercice_ref       INTEGER,
    type_exercice      VARCHAR(10) NOT NULL,
    categorie_exercice VARCHAR(10) NOT NULL,
    exercice_code      VARCHAR(50) NOT NULL,
    estimate_value     NUMERIC(1, 2),
    CONSTRAINT pk_exercices PRIMARY KEY (exercice_id),
    CONSTRAINT uq_exercices_1 UNIQUE (exercice_code),
    CONSTRAINT fk_exercices_1 FOREIGN KEY (exercice_ref) REFERENCES exercices (exercice_id),
    CONSTRAINT chk_exercices_1 CHECK (type_exercice IN ('SQUAT', 'PULL', 'SNATCH', 'CLEAN', 'JERK', 'MUSCU')),
    CONSTRAINT chk_exercices_2 CHECK (categorie_exercice IN ('TECH', 'COMBI', 'SEMI_LEGER', 'SEMI_LOURD', 'RENFO', 'GEN', 'LEG', 'POST', 'CORE', 'CARDIO', 'PLYO'))
);

COMMENT ON TABLE exercices IS 'Catalogue des exercices de référence';
COMMENT ON COLUMN exercices.exercice_ref IS 'Référence vers un exercice parent (auto-référence)';
COMMENT ON COLUMN exercices.type_exercice IS 'Type d''exercice : SQUAT, PULL, SNATCH, CLEAN, JERK, MUSCU';
COMMENT ON COLUMN exercices.categorie_exercice IS 'Catégorie d''exercice ou groupe musculaire : TECH, COMBI, SEMI_LEGER, SEMI_LOURD, RENFO, GEN, LEG, POST, CORE, CARDIO, PLYO';
COMMENT ON COLUMN exercices.exercice_code IS 'Code unique identifiant l exercice (voir libellé dans les fichiers i18n)';
COMMENT ON COLUMN exercices.estimate_value IS 'Charge théorique (% de l''exercice de référence)';

-- ------------------------------------------------------------
-- CORRECTION
-- Table de liaison exercice → exercices correctifs
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS corrections
(
    exercice_id   INTEGER NOT NULL,
    correction_id INTEGER NOT NULL,
    CONSTRAINT pk_corrections PRIMARY KEY (exercice_id, correction_id),
    CONSTRAINT fk_corrections_1 FOREIGN KEY (exercice_id) REFERENCES exercices (exercice_id),
    CONSTRAINT fk_corrections_2 FOREIGN KEY (correction_id) REFERENCES exercices (exercice_id)
);

COMMENT ON TABLE corrections IS 'Exercices correctifs associés à un exercice principal';

-- ------------------------------------------------------------
-- ATHLETE
-- Fiche athlète
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS athletes
(
    athlete_id       INTEGER GENERATED BY DEFAULT AS IDENTITY,
    first_name       VARCHAR(50) NOT NULL,
    last_name        VARCHAR(50) NOT NULL,
    sexe             VARCHAR(1)  NOT NULL,
    age_categorie    VARCHAR(10),
    weight_categorie INTEGER,
    comp_level       VARCHAR(10),
    CONSTRAINT pk_athletes PRIMARY KEY (athlete_id),
    CONSTRAINT chk_athletes_1 CHECK (sexe IN ('M', 'F')),
    CONSTRAINT chk_athletes_2 CHECK (age_categorie IN ('U15', 'U17', 'U20', 'SEN', 'MASTER')),
    CONSTRAINT chk_athletes_3 CHECK (weight_categorie IN (41, 45, 49, 51, 53, 55, 57, 60, 61, 65, 69, 70, 75, 77, 85, 86, 95, 110, 999)),
    CONSTRAINT chk_athletes_4 CHECK (comp_level IN ('DEB', 'DPT', 'REG', 'IRG', 'HON', 'NAT', 'EUR', 'MON'))
);

COMMENT ON TABLE athletes IS 'Fiche athlète OBC';
COMMENT ON COLUMN athletes.sexe IS 'M = Masculin, F = Féminin';
COMMENT ON COLUMN athletes.age_categorie IS 'Catégorie d âge : U15, U17, U20, SEN, MASTER';
COMMENT ON COLUMN athletes.weight_categorie IS 'Catégorie de poids | Hommes : 51, 55, 60, 65, 70, 75, 85, 95, 110, 999 (supérieur à 110) | Femmes : 41, 45, 49, 53, 57, 61, 69, 77, 86, 999 (supérieur à 86) ';
COMMENT ON COLUMN athletes.comp_level IS 'Niveau de compétition : DEB, DPT, REG, IRG, HON, NAT, EUR, MON';

-- ------------------------------------------------------------
-- REF_ARCHETYPE
-- Table de référence des archétypes force-vitesse
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ref_archetypes
(
    ref_archetype_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    archetype        VARCHAR(10) NOT NULL,
    strength_speed   VARCHAR(10)  NOT NULL,
    technique        VARCHAR(10)  NOT NULL,
    endurance        VARCHAR(10)  NOT NULL,
    CONSTRAINT pk_ref_archetypes PRIMARY KEY (ref_archetype_id),
    CONSTRAINT uq_ref_archetypes_1 UNIQUE (archetype, strength_speed, technique, endurance),
    CONSTRAINT chk_ref_archetypes_1 CHECK (strength_speed IN ('STRENGTH', 'MID', 'SPEED')),
    CONSTRAINT chk_ref_archetypes_2 CHECK (technique IN ('LOW', 'MID', 'HIGH')),
    CONSTRAINT chk_ref_archetypes_3 CHECK (endurance IN ('LOW', 'MID', 'HIGH')),
    CONSTRAINT chk_ref_archetypes_4 CHECK (archetype IN ('MID', 'ROUGH', 'TECH', 'CYCLE', 'LEARN'))
);

COMMENT ON TABLE ref_archetypes IS 'Table de référence des archétypes de profil athlète';
COMMENT ON COLUMN ref_archetypes.archetype IS 'Nom de l''archétype : MID, ROUGH, TECH, CYCLE, LEARN';
COMMENT ON COLUMN ref_archetypes.strength_speed IS 'Niveau force-vitesse : STRENGTH, MID, SPEED';
COMMENT ON COLUMN ref_archetypes.technique IS 'Niveau technique : LOW, MID, HIGH';
COMMENT ON COLUMN ref_archetypes.endurance IS 'Niveau endurance : LOW, MID, HIGH';

-- ------------------------------------------------------------
-- EVAL_SUMMARY
-- Bilan d évaluation d un athlète
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS eval_summaries
(
    evaluation_id    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    athlete_id       INTEGER NOT NULL,
    evaluation_date  DATE NOT NULL,
    archetype        VARCHAR(10),
    strength_speed   VARCHAR(10),
    technique        VARCHAR(10),
    endurance        VARCHAR(10),
    squat            VARCHAR(10),
    pull             VARCHAR(10),
    snatch_strength  VARCHAR(100),
    snatch_weakness  VARCHAR(100),
    clean_strength   VARCHAR(100),
    clean_weakness   VARCHAR(100),
    jerk_strength    VARCHAR(100),
    jerk_weakness    VARCHAR(100),
    psycho_strength  VARCHAR(100),
    psycho_weakness  VARCHAR(100),
    CONSTRAINT pk_eval_summaries PRIMARY KEY (evaluation_id),
    CONSTRAINT fk_eval_summaries_1 FOREIGN KEY (athlete_id) REFERENCES athletes (athlete_id)
);

COMMENT ON TABLE eval_summaries IS 'Bilan synthétique d une évaluation athlète';
COMMENT ON COLUMN eval_summaries.archetype IS 'Archétype résultant de l''évaluation : MID, ROUGH, TECH, CYCLE, LEARN';
COMMENT ON COLUMN eval_summaries.strength_speed IS 'Profil force-vitesse : STRENGTH, MID, SPEED';
COMMENT ON COLUMN eval_summaries.technique IS 'Profil technique : LOW, MID, HIGH';
COMMENT ON COLUMN eval_summaries.endurance IS 'Profil endurance : LOW, MID, HIGH';
COMMENT ON COLUMN eval_summaries.squat IS 'Profil squat : STRENGTH, MID, SPEED';
COMMENT ON COLUMN eval_summaries.pull IS 'Profil tirage : STRENGTH, MID, SPEED';
COMMENT ON COLUMN eval_summaries.snatch_strength IS 'Point fort à l''arraché';
COMMENT ON COLUMN eval_summaries.snatch_weakness IS 'Point faible à l''arraché';
COMMENT ON COLUMN eval_summaries.clean_strength IS 'Point fort à l''épaulé';
COMMENT ON COLUMN eval_summaries.clean_weakness IS 'Point faible à l''épaulé';
COMMENT ON COLUMN eval_summaries.jerk_strength IS 'Point fort au jeté';
COMMENT ON COLUMN eval_summaries.jerk_weakness IS 'Point faible au jeté';
COMMENT ON COLUMN eval_summaries.psycho_strength IS 'Point fort psychologique : CALM, CONFIDENT, MOTIVATED, FOCUSED, COMPETITIVE, CHALLENGER, INDEPENDANT';
COMMENT ON COLUMN EVAL_SUMMARIES.psycho_weakness IS 'Point faible psychologique : EMOTIONAL, ANXIOUS, INDIFFERENT, DISTRACTED, HEDONISTIC, PRAGMATIC, RULE';

CREATE INDEX IF NOT EXISTS idx_eval_summaries_1 ON eval_summaries (athlete_id);
CREATE INDEX IF NOT EXISTS idx_eval_summaries_2 ON eval_summaries (evaluation_date);

-- ------------------------------------------------------------
-- EVAL_DETAIL
-- Détail des mesures par évaluation
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS eval_details
(
    evaluation_detail_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    evaluation_id        INTEGER NOT NULL,
    eval_categorie       VARCHAR(10) NOT NULL,
    exercice_code        VARCHAR(50),
    real_value           NUMERIC(10, 4),
    result               INTEGER,
    CONSTRAINT pk_eval_details PRIMARY KEY (evaluation_detail_id),
    CONSTRAINT fk_eval_details_1 FOREIGN KEY (evaluation_id) REFERENCES eval_summaries (evaluation_id)
);

COMMENT ON TABLE eval_details IS 'Détail des mesures réalisées lors d une évaluation';
COMMENT ON COLUMN eval_details.eval_categorie IS 'Catégorie de l évaluation : STRENGTH, TECH, CARDIO, PSYCHO';
COMMENT ON COLUMN eval_details.exercice_code IS 'Code de l''exercice évalué';
COMMENT ON COLUMN eval_details.real_value IS 'Valeur mesurée (kg, m/s, %, reps, etc.)';
COMMENT ON COLUMN eval_details.result IS 'Résultat calculé : LOW (-1), MID (0), HIGH (1)';

CREATE INDEX IF NOT EXISTS idx_eval_details_1 ON eval_details (evaluation_id);

-- ------------------------------------------------------------
-- PROG
-- Programme d entraînement généré à partir d une évaluation
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS programmes
(
    programme_id  INTEGER GENERATED BY DEFAULT AS IDENTITY,
    evaluation_id INTEGER NOT NULL,
    weeks         INTEGER NOT NULL,
    frequency     INTEGER NOT NULL,
    duration      INTEGER,
    start_date    DATE NOT NULL,
    end_date      DATE NOT NULL,
    snatch_goal   INTEGER,
    cj_goal       INTEGER,
    CONSTRAINT pk_programmes PRIMARY KEY (programme_id),
    CONSTRAINT chk_programmes_1 CHECK (weeks > 0),
    CONSTRAINT chk_programmes_2 CHECK (frequency BETWEEN 3 AND 5),
    CONSTRAINT chk_programmes_3 CHECK (duration BETWEEN 90 AND 150),
    CONSTRAINT chk_programmes_4 CHECK (end_date >= start_date),
    CONSTRAINT chk_programmes_5 CHECK (snatch_goal > 0),
    CONSTRAINT chk_programmes_6 CHECK (cj_goal > 0),
    CONSTRAINT fk_programmes_1 FOREIGN KEY (evaluation_id) REFERENCES eval_summaries (evaluation_id)
);

COMMENT ON TABLE programmes IS 'Programme d entraînement généré pour un athlète';
COMMENT ON COLUMN programmes.weeks IS 'Nombre de semaines du programme: 8, 12, 16';
COMMENT ON COLUMN programmes.frequency IS 'Nombre de séances par semaine: 3, 4, 5';
COMMENT ON COLUMN programmes.duration IS 'Durée d''une séance en minutes : 90, 120, 150';
COMMENT ON COLUMN programmes.start_date IS 'Date de début du programme';
COMMENT ON COLUMN programmes.end_date IS 'Date de fin du programme';
COMMENT ON COLUMN programmes.snatch_goal IS 'Objectif arraché en kg';
COMMENT ON COLUMN programmes.cj_goal IS 'Objectif épaulé-jeté en kg';

CREATE INDEX IF NOT EXISTS idx_programmes_1 ON programmes (evaluation_id);

-- ------------------------------------------------------------
-- PROG_WEEK
-- Semaine d entraînement dans un programme
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS programme_weeks
(
    programme_week_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    programme_id      INTEGER NOT NULL,
    week_number       INTEGER NOT NULL,
    start_date        DATE NOT NULL,
    end_date          DATE NOT NULL,
    week_type         VARCHAR(50) NOT NULL,
    base_percent      NUMERIC(1,2) NOT NULL,
    snatch_goal       INTEGER NOT NULL,
    cj_goal           INTEGER NOT NULL,
    back_squat_goal   INTEGER NOT NULL,
    front_squat_goal  INTEGER NOT NULL,
    snatch_pull_goal  INTEGER NOT NULL,
    cj_pull_goal      INTEGER NOT NULL,
    CONSTRAINT pk_programme_weeks PRIMARY KEY (programme_week_id),
    CONSTRAINT uq_programme_weeks_1 UNIQUE (programme_id, week_number),
    CONSTRAINT chk_programme_weeks_1 CHECK (week_number BETWEEN 1 AND 16),
    CONSTRAINT chk_programme_weeks_2 CHECK (base_percent > 0),
    CONSTRAINT chk_programme_weeks_3 CHECK (end_date >= start_date),
    CONSTRAINT chk_programme_weeks_4 CHECK (week_type IN ('VOLUME', 'TECH', 'STRENGTH', 'PEAK', 'DELOAD')),
    CONSTRAINT fk_programme_weeks_1 FOREIGN KEY (programme_id) REFERENCES programmes (programme_id)
);

COMMENT ON TABLE programme_weeks IS 'Découpage hebdomadaire d''un programme';
COMMENT ON COLUMN programme_weeks.week_type IS 'Type de semaine : VOLUME (F), TECH (T), STRENGTH (S), PEAK (A), DELOAD (D)';
COMMENT ON COLUMN programme_weeks.base_percent IS 'Pourcentage de l''objectif final';
COMMENT ON COLUMN programme_weeks.snatch_goal IS 'Base pour l''arraché';
COMMENT ON COLUMN programme_weeks.cj_goal IS 'Base pour l''épaulé-jeté';
COMMENT ON COLUMN programme_weeks.back_squat_goal IS 'Base pour le squat nuque';
COMMENT ON COLUMN programme_weeks.front_squat_goal IS 'Base pour les squat clavicule';
COMMENT ON COLUMN programme_weeks.snatch_pull_goal IS 'Base pour les tirages d''arraché';
COMMENT ON COLUMN programme_weeks.cj_pull_goal IS 'Base pour les tirages d''épaulé';

CREATE INDEX IF NOT EXISTS idx_programme_weeks_1 ON programme_weeks (programme_id);

-- ------------------------------------------------------------
-- PROG_TRAINING
-- Exercice planifié dans une séance hebdomadaire
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS programme_trainings
(
    programme_training_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    programme_week_id     INTEGER NOT NULL,
    training_number       INTEGER NOT NULL,
    exercice_order        INTEGER NOT NULL,
    exercice_code         VARCHAR(50) NOT NULL,
    set_number            INTEGER NOT NULL,
    rep_number            INTEGER NOT NULL,
    rep_label             VARCHAR(20),
    min_weight            NUMERIC(6, 2),
    max_weight            NUMERIC(6, 2),
    CONSTRAINT pk_programme_trainings PRIMARY KEY (programme_training_id),
    CONSTRAINT chk_programme_trainings_1 CHECK (exercice_order > 0),
    CONSTRAINT chk_programme_trainings_2 CHECK (set_number > 0),
    CONSTRAINT chk_programme_trainings_3 CHECK (rep_number > 0),
    CONSTRAINT chk_programme_trainings_4 CHECK (max_weight IS NULL OR max_weight >= min_weight),
    CONSTRAINT chk_programme_trainings_5 CHECK (training_number BETWEEN 1 AND 5),
    CONSTRAINT fk_programme_trainings_1 FOREIGN KEY (programme_week_id) REFERENCES programme_weeks (programme_week_id)
);

COMMENT ON TABLE programme_trainings IS 'Exercices planifiés dans une semaine de programme';
COMMENT ON COLUMN programme_trainings.training_number IS 'Numéro de la séance hebdomadaire';
COMMENT ON COLUMN programme_trainings.exercice_order IS 'Ordre de l''exercice dans la séance (si plusieurs fois le même ordre => "Au choix")';
COMMENT ON COLUMN programme_trainings.exercice_code IS 'Code unique identifiant l''exercice (voir libellé dans les fichiers i18n)';
COMMENT ON COLUMN programme_trainings.set_number IS 'Nombre de séries';
COMMENT ON COLUMN programme_trainings.rep_number IS 'Nombre de répétitions par série';
COMMENT ON COLUMN programme_trainings.rep_label IS 'Label des répétitions (si complexe, ex : "30s + 10 reps")';
COMMENT ON COLUMN programme_trainings.min_weight IS 'Charge minimale en kg';
COMMENT ON COLUMN programme_trainings.max_weight IS 'Charge maximale en kg';

CREATE INDEX IF NOT EXISTS idx_programme_trainings_1 ON programme_trainings (programme_week_id);

-- ------------------------------------------------------------
-- REF_TIMELINE
-- Table de référence des timelines par archétype et durée
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ref_timelines
(
    ref_timeline_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    archetype       VARCHAR(10)  NOT NULL,
    weeks           INTEGER      NOT NULL,
    timeline        VARCHAR(255) NOT NULL,
    CONSTRAINT pk_ref_timelines PRIMARY KEY (ref_timeline_id),
    CONSTRAINT uq_ref_timelines_1 UNIQUE (archetype, weeks),
    CONSTRAINT chk_ref_timelines_1 CHECK (archetype IN ('MID', 'ROUGH', 'TECH', 'CYCLE', 'LEARN')),
    CONSTRAINT chk_ref_timelines_2 CHECK (weeks IN (8, 12, 16))
);

COMMENT ON TABLE ref_timelines IS 'Timelines de référence par archétype et durée de programme';
COMMENT ON COLUMN ref_timelines.archetype IS 'Archétype de l''athlète : MID, ROUGH, TECH, CYCLE, LEARN';
COMMENT ON COLUMN ref_timelines.weeks IS 'Nombre de semaines du programme : 8, 12, 16';
COMMENT ON COLUMN ref_timelines.timeline IS 'Séquence de types de semaines : VOLUME (F), TECH (T), STRENGTH (S), PEAK (A), DELOAD (D)';

-- ------------------------------------------------------------
-- REF_PLANNING
-- Planification de référence par timeline et semaine
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ref_plannings
(
    ref_planning_id    BIGINT GENERATED ALWAYS AS IDENTITY,
    ref_timeline_id    BIGINT       NOT NULL,
    week_type          VARCHAR(50)  NOT NULL,
    day_of_week        INTEGER      NOT NULL,
    exercice_order     INTEGER      NOT NULL,
    categorie_exercice VARCHAR(100) NOT NULL,
    type_exercice      VARCHAR(100),
    strength_weakness  VARCHAR(10),
    set_number         INTEGER,
    rep_number         INTEGER,
    rep_label          VARCHAR(20),
    CONSTRAINT pk_ref_plannings PRIMARY KEY (ref_planning_id),
    CONSTRAINT chk_ref_plannings_1 CHECK (day_of_week BETWEEN 1 AND 5),
    CONSTRAINT chk_ref_plannings_2 CHECK (exercice_order > 0),
    CONSTRAINT chk_ref_plannings_3 CHECK (set_number > 0),
    CONSTRAINT chk_ref_plannings_4 CHECK (rep_number > 0),
    CONSTRAINT chk_ref_plannings_5 CHECK (strength_weakness IN ('STRENGTH', 'WEAKNESS', NULL)),
    CONSTRAINT fk_ref_plannings_1 FOREIGN KEY (ref_timeline_id) REFERENCES ref_timelines (ref_timeline_id)
);

COMMENT ON TABLE ref_plannings IS 'Planning de référence associé à une timeline';
COMMENT ON COLUMN ref_plannings.week_type IS 'Type de semaine : VOLUME (F), TECH (T), STRENGTH (S), PEAK (A), DELOAD (D)';
COMMENT ON COLUMN ref_plannings.day_of_week IS 'Numéro de la séance dans la semaine';
COMMENT ON COLUMN ref_plannings.exercice_order IS 'Ordre de passage dans la séance, si plusieurs => "Au choix"';
COMMENT ON COLUMN ref_plannings.categorie_exercice IS 'Catégorie d''exercice attendue';
COMMENT ON COLUMN ref_plannings.type_exercice IS 'Type d''exercice attendu';
COMMENT ON COLUMN ref_plannings.strength_weakness IS 'STRENGTH = point fort, WEAKNESS = point faible';
COMMENT ON COLUMN ref_plannings.set_number IS 'Nombre de séries de référence';
COMMENT ON COLUMN ref_plannings.rep_number IS 'Nombre de répétitions de référence';
COMMENT ON COLUMN ref_plannings.rep_label IS 'Label des répétitions de référence';

CREATE INDEX IF NOT EXISTS idx_ref_plannings_1 ON ref_plannings (ref_timeline_id);
CREATE INDEX IF NOT EXISTS idx_ref_plannings_2 ON ref_plannings (week_type);